# Generated by Django 4.2.2 on 2023-06-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TerceraPreEntregaPalazzoeboApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
