# Generated by Django 4.2.2 on 2023-07-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TerceraPreEntregaPalazzoApp', '0002_delete_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
    ]
