# Generated by Django 4.2.2 on 2023-07-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TerceraPreEntregaPalazzoApp', '0004_detalleventa_preciofinal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
